GET http://localhost:5000/adadasd

###
GET http://localhost:5000/api/v1/user/

###
POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
  "email": "duynghia@gmail.com",
  "password": "123456"
}

###
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "email": "duynghia@gmail.com",
  "password": "123456"
}

###
GET http://localhost:5000/api/v1/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJkdXluZ2hpYUBnbWFpbC5jb20iLCJyb2xlX2NvZGUiOiJSMyIsImlhdCI6MTY2NTgyMDMxNSwiZXhwIjoxNjY1ODIwMzIwfQ.gldbTzM0EpBQbEFy4q2ToKkcrtrcIgMU3-cghisS-a0

###
GET http://localhost:5000/api/v1/insert/

###
GET http://localhost:5000/api/v1/book/