export const FAKE_STUDENT_LIST = [
  {
    _id: '603932a4b984e481a3e36163',
    index: 0,
    guid: 'c4f18ea1-4678-42c9-b9bf-8beb6ffefedf',
    isActive: true,
    balance: '$1,965.46',
    picture: 'http://placehold.it/32x32',
    age: 20,
    eyeColor: 'brown',
    name: {
      first: 'Claire',
      last: 'Luna',
    },
    company: 'SUPPORTAL',
    email: 'claire.luna@supportal.biz',
    phone: '+1 (987) 539-3276',
    address: '778 Lawrence Street, Lafferty, Idaho, 4588',
    about:
      'Adipisicing culpa tempor consequat culpa nulla minim laboris ullamco commodo labore et commodo Lorem. Nostrud cupidatat occaecat qui magna dolore duis nulla consequat. Tempor exercitation aute nostrud eiusmod velit cillum eu non. Cupidatat aliqua duis sint magna aliqua enim qui adipisicing velit. Et ad sunt fugiat incididunt nostrud nisi duis id sunt ut elit. Elit mollit ipsum voluptate occaecat culpa.',
    registered: 'Wednesday, March 18, 2015 10:43 PM',
    latitude: '-79.666498',
    longitude: '-124.883685',
    tags: ['est', 'aliqua', 'adipisicing', 'sunt', 'cillum'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Gay Atkinson',
      },
      {
        id: 1,
        name: 'Velma Hammond',
      },
      {
        id: 2,
        name: 'Marietta Bryant',
      },
    ],
    greeting: 'Hello, Claire! You have 9 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '603932a415789cf2be8a8381',
    index: 1,
    guid: '6218a12c-d9c7-4f89-b5e4-ce4b383985ac',
    isActive: true,
    balance: '$1,610.91',
    picture: 'http://placehold.it/32x32',
    age: 33,
    eyeColor: 'brown',
    name: {
      first: 'Mason',
      last: 'Alvarado',
    },
    company: 'POWERNET',
    email: 'mason.alvarado@powernet.me',
    phone: '+1 (959) 547-2878',
    address: '546 Bassett Avenue, Bonanza, Kansas, 8223',
    about:
      'Esse incididunt enim commodo veniam qui commodo nulla cupidatat eiusmod quis eiusmod exercitation. Dolor et dolor sunt dolore incididunt. Voluptate officia aliqua qui commodo. Amet proident labore et voluptate excepteur reprehenderit minim in sunt.',
    registered: 'Wednesday, August 19, 2015 9:44 PM',
    latitude: '28.080297',
    longitude: '-15.49025',
    tags: ['excepteur', 'duis', 'ut', 'ea', 'non'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Ellis Valenzuela',
      },
      {
        id: 1,
        name: 'Aguilar Baxter',
      },
      {
        id: 2,
        name: 'Cummings Barton',
      },
    ],
    greeting: 'Hello, Mason! You have 10 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '603932a461900bfb17ec7c4b',
    index: 2,
    guid: '4298256c-6bec-415c-86f1-a3cd329b55fa',
    isActive: true,
    balance: '$1,565.84',
    picture: 'http://placehold.it/32x32',
    age: 39,
    eyeColor: 'blue',
    name: {
      first: 'Boyer',
      last: 'Long',
    },
    company: 'BISBA',
    email: 'boyer.long@bisba.net',
    phone: '+1 (866) 428-2345',
    address: '781 Ludlam Place, Wollochet, Tennessee, 6202',
    about:
      'Mollit cupidatat sit deserunt labore cupidatat et consectetur est nulla quis excepteur ad adipisicing. Sunt pariatur esse ad sint. Officia nisi dolor occaecat dolore laborum et id minim ullamco ut sunt incididunt pariatur. Enim sit in sit culpa nisi sit eiusmod minim anim duis. Eu eiusmod adipisicing pariatur ullamco est amet excepteur in commodo id esse sit aliqua ullamco. Anim proident Lorem consequat ea.',
    registered: 'Saturday, August 25, 2018 11:03 PM',
    latitude: '-40.795587',
    longitude: '18.138553',
    tags: ['culpa', 'ad', 'esse', 'fugiat', 'minim'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Cecelia Mason',
      },
      {
        id: 1,
        name: 'Glenda Knight',
      },
      {
        id: 2,
        name: 'Hurley Christensen',
      },
    ],
    greeting: 'Hello, Boyer! You have 7 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '603932a4a08d896a91a9152f',
    index: 3,
    guid: 'abd6e633-9a2d-42a0-baea-873a012a9772',
    isActive: false,
    balance: '$1,769.99',
    picture: 'http://placehold.it/32x32',
    age: 20,
    eyeColor: 'blue',
    name: {
      first: 'Lula',
      last: 'Munoz',
    },
    company: 'QIMONK',
    email: 'lula.munoz@qimonk.tv',
    phone: '+1 (800) 510-3758',
    address: '784 Bartlett Place, Robbins, Palau, 9697',
    about:
      'Lorem nisi non culpa ad sit culpa et Lorem esse nostrud duis ea velit et. Incididunt consequat consequat officia nulla et do cupidatat aute do reprehenderit ea ex velit amet. Consectetur excepteur aliqua reprehenderit incididunt sint nulla laboris veniam. Commodo ea irure Lorem commodo nostrud minim consequat mollit eu enim excepteur anim duis. Consequat aute Lorem id ex consequat sit aliqua ullamco. Commodo anim ipsum Lorem cupidatat consequat deserunt magna officia ex.',
    registered: 'Wednesday, July 16, 2014 6:41 AM',
    latitude: '-51.729482',
    longitude: '-93.093494',
    tags: ['ullamco', 'dolor', 'eiusmod', 'ex', 'cillum'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Lora Jennings',
      },
      {
        id: 1,
        name: 'Queen Frost',
      },
      {
        id: 2,
        name: 'Goodman Snyder',
      },
    ],
    greeting: 'Hello, Lula! You have 10 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '603932a48c0a4fe97d45aa02',
    index: 4,
    guid: 'fb1c52c0-df46-48d2-baa4-58984a6fb056',
    isActive: true,
    balance: '$2,104.25',
    picture: 'http://placehold.it/32x32',
    age: 35,
    eyeColor: 'brown',
    name: {
      first: 'Bobbie',
      last: 'Gay',
    },
    company: 'KNOWLYSIS',
    email: 'bobbie.gay@knowlysis.io',
    phone: '+1 (990) 494-2596',
    address: '496 Mill Avenue, Barclay, Georgia, 1951',
    about:
      'Occaecat id laborum ea ex aliquip magna labore aliqua mollit. Ut duis aliquip culpa proident adipisicing pariatur est cupidatat dolore Lorem mollit reprehenderit dolor. Nostrud sint magna duis consectetur eu sint et officia aliqua adipisicing culpa.',
    registered: 'Monday, April 9, 2018 5:04 PM',
    latitude: '-44.873511',
    longitude: '139.473422',
    tags: ['ipsum', 'sit', 'labore', 'exercitation', 'eu'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Jana Sanders',
      },
      {
        id: 1,
        name: 'Alston Love',
      },
      {
        id: 2,
        name: 'Sellers Robles',
      },
    ],
    greeting: 'Hello, Bobbie! You have 9 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '603932a423092facbc78a758',
    index: 5,
    guid: '8075c6f8-2c45-42b3-968e-41918399f579',
    isActive: true,
    balance: '$2,422.29',
    picture: 'http://placehold.it/32x32',
    age: 31,
    eyeColor: 'blue',
    name: {
      first: 'Carolyn',
      last: 'Bray',
    },
    company: 'PLASMOX',
    email: 'carolyn.bray@plasmox.info',
    phone: '+1 (911) 414-3662',
    address: '746 Beverly Road, Condon, Alabama, 3658',
    about:
      'Nisi incididunt excepteur incididunt reprehenderit Lorem elit velit nulla adipisicing ullamco ut qui aliqua dolore. Adipisicing laboris sint esse eu mollit sunt culpa est pariatur mollit proident. Velit incididunt et id ullamco non deserunt deserunt in amet velit consectetur ex.',
    registered: 'Wednesday, May 17, 2017 7:32 AM',
    latitude: '41.938169',
    longitude: '1.007749',
    tags: ['minim', 'ad', 'cupidatat', 'proident', 'officia'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Doris Goff',
      },
      {
        id: 1,
        name: 'Cobb Woods',
      },
      {
        id: 2,
        name: 'Solis Davidson',
      },
    ],
    greeting: 'Hello, Carolyn! You have 10 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '603932a43d7ff0bb1eef572e',
    index: 6,
    guid: 'd95192fe-76f8-41a5-834b-208a080f0eb9',
    isActive: false,
    balance: '$2,959.92',
    picture: 'http://placehold.it/32x32',
    age: 20,
    eyeColor: 'blue',
    name: {
      first: 'Lela',
      last: 'Patton',
    },
    company: 'PORTICA',
    email: 'lela.patton@portica.com',
    phone: '+1 (915) 406-2187',
    address: '687 Village Road, Remington, Connecticut, 7801',
    about:
      'Do nisi nulla dolor ex laboris laboris officia voluptate nisi est culpa in dolor aliquip. Anim ut quis nisi nulla incididunt aute enim eu mollit. Et in ad nulla qui cillum ex sit esse commodo do officia amet nisi. Culpa labore veniam esse dolor consectetur magna dolor officia culpa commodo pariatur do. Laborum tempor laboris consectetur velit eiusmod dolore esse aliquip velit. Fugiat culpa eu nisi occaecat do magna.',
    registered: 'Thursday, August 27, 2015 10:15 PM',
    latitude: '-2.93045',
    longitude: '-134.431925',
    tags: ['proident', 'reprehenderit', 'duis', 'mollit', 'ea'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Lott Ferguson',
      },
      {
        id: 1,
        name: 'Sue Bullock',
      },
      {
        id: 2,
        name: 'Rosetta Underwood',
      },
    ],
    greeting: 'Hello, Lela! You have 8 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '603932a41f2a0506fad7e700',
    index: 7,
    guid: 'c56a6024-88b8-4767-926a-f7caaae4d2f6',
    isActive: true,
    balance: '$3,066.09',
    picture: 'http://placehold.it/32x32',
    age: 26,
    eyeColor: 'brown',
    name: {
      first: 'Hopkins',
      last: 'Castillo',
    },
    company: 'LIMAGE',
    email: 'hopkins.castillo@limage.us',
    phone: '+1 (990) 537-2325',
    address: '854 Willmohr Street, Lisco, Virginia, 5310',
    about:
      'Reprehenderit dolore velit duis ut excepteur reprehenderit nulla minim. Sint do voluptate aliqua labore. Cupidatat velit aliquip ipsum laborum eu tempor ut ullamco. Consectetur irure nostrud culpa Lorem aliquip est ullamco quis occaecat ad esse quis.',
    registered: 'Saturday, October 5, 2019 6:42 AM',
    latitude: '4.096474',
    longitude: '-68.164304',
    tags: ['Lorem', 'aute', 'sunt', 'dolor', 'cillum'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Ella Berger',
      },
      {
        id: 1,
        name: 'Sheppard Mendoza',
      },
      {
        id: 2,
        name: 'Michelle Gillespie',
      },
    ],
    greeting: 'Hello, Hopkins! You have 5 unread messages.',
    favoriteFruit: 'banana',
  },
];
