export const SET_AUTHED_USER = 'SET_AUTHED_USER';

export const GET_QUESTIONS = 'GET_QUESTIONS';
export const ADD_QUESTION = 'SAVE_QUESTION';
export const ADD_QUESTION_ANSWER = 'ADD_QUESTION_ANSWER';

export const GET_USERS = 'GET_USERS';
export const ADD_ANSWER_TO_USER = 'ADD_ANSWER_TO_USER';
export const ADD_QUESTION_TO_USER = 'ADD_QUESTION_TO_USER';
