export const BOOKS = [
    {
      id: 1,
      name: 'Refactoring',
      author: 'Martin Fowler',
      topic: 'Programming',
    },
    {
      id: 2,
      name: 'Designing Data-Intensive Applications',
      author: 'Martin Kleppmann',
      topic: 'Database',
    },
    {
      id: 3,
      name: 'The Phoenix Project',
      author: 'Gene Kim',
      topic: 'DevOps',
    },
    {
      id: 4,
      name: 'A Handbook of Agile Software Craftsmanship',
      author: 'Robert C. Martin',
      topic: 'Programming',
    },
    {
      id: 5,
      name: 'Introduction to the Theory of Computation',
      author: 'Michael Sipser',
      topic: 'Computer Science',
    },
    {
      id: 6,
      name: 'A Practical Handbook of Software Construction',
      author: 'Steve McConnell',
      topic: 'Programming',
    },
    {
      id: 7,
      name: 'Cracking the Coding Interview',
      author: 'Gayle L. McDowell',
      topic: 'Programming',
    },
    {
      id: 8,
      name: 'The Art of Computer Programming',
      author: 'Donald E. Knuth',
      topic: 'Computer Science',
    },
    {
      id: 9,
      name: 'Head First Design Patterns',
      author: 'Eric Freeman',
      topic: 'Design Patterns',
    },
    {
      id: 10,
      name: 'A Craftsman\'s Guide to Software Structure and Design',
      author: 'Robert C. Martin',
      topic: 'Software Architecture',
    },
    {
      id: 11,
      name: 'A Deep Dive into How Distributed Data Systems Work',
      author: 'Alex Petrov',
      topic: 'Database',
    },
    {
      id: 12,
      name: 'Reliable Software Releases through Build and Test',
      author: 'Jez Humble',
      topic: 'DevOps',
    },
    {
      id: 13,
      name: 'Effective Java',
      author: 'Joshua Bloch',
      topic: 'Programming',
    },
    {
      id: 14,
      name: 'Algorithms',
      author: 'Robert Sedgewick',
      topic: 'Algorithms',
    },
    {
      id: 15,
      name: 'Your Journey to Mastery',
      author: 'Andrew Hunt',
      topic: 'Programming',
    },
    {
      id: 16,
      name: 'Operating System Concepts',
      author: 'Greg Gagne',
      topic: 'Operating Systems',
    },
    {
      id: 17,
      name: 'Introduction to Algorithms',
      author: 'Thomas H. Cormen',
      topic: 'Algorithms',
    },
    {
      id: 18,
      name: 'Essays on Software Engineering',
      author: 'Frederick P. Brooks Jr.',
      topic: 'Software Engineering',
    },
    {
      id: 19,
      name: 'Docker Deep Dive',
      author: 'Nigel Poulton',
      topic: 'Docker',
    },
    {
      id: 20,
      name: 'Introduction to DevOps with Docker',
      author: 'Viktor Farcic',
      topic: 'DevOps',
    },
    {
      id: 21,
      name: 'The Good Parts',
      author: 'Douglas Crockford',
      topic: 'Programming',
    },
    {
      id: 22,
      name: '90 Specific Ways to Write Better Python',
      author: 'Brett Slatkin',
      topic: 'Programming',
    },
    {
      id: 23,
      name: 'Linux Kernel Development',
      author: 'Robert Love',
      topic: 'Linux',
    },
    {
      id: 24,
      name: 'A Modern Approach',
      author: 'Stuart Russell',
      topic: 'AI',
    },
    {
      id: 25,
      name: 'Pro Git',
      author: 'Scott Chacon',
      topic: 'Version Control',
    },
    {
      id: 26,
      name: 'Introduction to Machine Learning with Python',
      author: 'Andreas C. Müller',
      topic: 'Machine Learning',
    },
    {
      id: 27,
      name: 'The C Programming Language',
      author: 'Brian W. Kernighan',
      topic: 'Programming',
    },
    {
      id: 28,
      name: 'Deep Learning',
      author: 'Ian Goodfellow',
      topic: 'Deep Learning',
    },
    {
      id: 29,
      name: 'Mastering Git',
      author: 'Scott Chacon',
      topic: 'Version Control',
    },
    {
      id: 30,
      name: 'Introduction to Kubernetes',
      author: 'Artemii Kropachev',
      topic: 'Kubernetes',
    },
    {
      id: 31,
      name: 'Introduction to Rust Programming',
      author: 'Steve Klabnik',
      topic: 'Programming',
    },
    {
      id: 32,
      name: 'Clean Agile: Back to Basics',
      author: 'Robert C. Martin',
      topic: 'Programming',
    },
    {
      id: 33,
      name: 'Effective TypeScript',
      author: 'Dan Vanderkam',
      topic: 'Programming',
    },
    {
      id: 34,
      name: 'Kafka: The Definitive Guide',
      author: 'Gwen Shapira',
      topic: 'Apache Kafka',
    },
    {
      id: 35,
      name: 'Learning SQL',
      author: 'Alan Beaulieu',
      topic: 'SQL',
    },
    {
      id: 36,
      name: 'Improving Software Quality and Reducing Risk',
      author: 'Paul M. Duvall',
      topic: 'Programming',
    },
    {
      id: 37,
      name: 'Automate the Boring Stuff with Python',
      author: 'Al Sweigart',
      topic: 'Programming',
    },
    {
      id: 38,
      name: 'Containerization is the new virtualization',
      author: 'James Turnbull',
      topic: 'Docker',
    },
    {
      id: 39,
      name: 'Introduction to AI',
      author: 'Wolfgang Ertel',
      topic: 'AI',
    },
    {
      id: 40,
      name: 'Mastering Kubernetes',
      author: 'Gigi Sayfan',
      topic: 'Kubernetes',
    },
  ];
  