export const actionTypes = {
  // GET_ALL_USERS: "GET_ALL_USERS",
  // ADD_USER: "ADD_USER",
  // EDIT_USER: "EDIT_USER",
  // DELETE_USER: "DELETE_USER",
  GET_ALL_USERS_SUCCESS: "GET_ALL_USERS_SUCCESS",
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
};
