export const metadata = {
  title: 'Blog Lists',
  description: 'Generated by Duy Nghia Dev'
}

export default function BlogLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>
}
