export const metadata = {
  title: 'View Detail Blog',
  description: 'Generated by Duy Nghia Dev'
}

export default function ViewDetailLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>
}
