import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from 'react'
import ReduxProvider from './store/ReduxProvider'
import QueryProvider from './QueryProvider'
import ProviderTheme from './ThemeProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Books store',
  description: 'Generated by create next app',
}

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderTheme>
          <QueryProvider>
            <ReduxProvider>{props.children}</ReduxProvider>
          </QueryProvider>
        </ProviderTheme>
      </body>
    </html>
  )
}
