export const ACTION_TYPES = {
  SET_ALL_PRODUCTS: "SET_ALL_PRODUCTS",
  SET_CURRENT_PRODUCT: "SET_CURRENT_PRODUCT",
  REMOVE_CURRENT_PRODUCT: "REMOVE_CURRENT_PRODUCT",
  FETCH_ALL_PRODUCTS: "SET_ALL_PRODUCTS",
};
