version: '3'
services:
  app:
    container_name: go_live_web
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - '3002:3002'
    volumes:
      - .:/app
    command: yarn dev
