import { BookList } from '../../types'

export const GENRES = [
  'Science',
  'Technology',
  'Literature',
  'Economics',
  'History',
  'Mystery',
  'Romance',
  'Fantasy',
  'Adventure',
  'Horror',
  'Biography',
  'Self-Help',
  'Cooking',
  'Travel',
  'Science Fiction',
  'Thriller',
  'Minimalism',
  'Software Development',
  'Web Development',
  'Algorithms',
  'Java Programming',
]

export const BOOK_LIST: BookList = [
  {
    id: 1,
    title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    author: 'Robert C. Martin',
    genre: 'Software Development',
  },
  {
    id: 2,
    title: 'JavaScript The Good Parts',
    author: 'Douglas Crockford',
    genre: 'Web Development',
  },
  {
    id: 3,
    title: 'Introduction to Algorithms',
    author:
      'Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein',
    genre: 'Algorithms',
  },
  {
    id: 4,
    title: 'The Pragmatic Programmer: Your Journey to Mastery',
    author: 'Andrew Hunt, David Thomas',
    genre: 'Software Development',
  },
  {
    id: 5,
    title: 'Effective Java',
    author: 'Joshua Bloch',
    genre: 'Java Programming',
  },
  {
    id: 6,
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    genre: 'Literature',
  },
  {
    id: 7,
    title: '1984',
    author: 'George Orwell',
    genre: 'Science Fiction',
  },
  {
    id: 8,
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    genre: 'Literature',
  },
  {
    id: 9,
    title: 'One Hundred Years of Solitude',
    author: 'Gabriel García Márquez',
    genre: 'Literature',
  },
  {
    id: 10,
    title: 'Brave New World',
    author: 'Aldous Huxley',
    genre: 'Science Fiction',
  },
  {
    id: 11,
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    genre: 'Literature',
  },
  {
    id: 12,
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    genre: 'Literature',
  },
  {
    id: 13,
    title: 'To the Lighthouse',
    author: 'Virginia Woolf',
    genre: 'Literature',
  },
  {
    id: 14,
    title: 'War and Peace',
    author: 'Leo Tolstoy',
    genre: 'Literature',
  },
  {
    id: 15,
    title: 'Crime and Punishment',
    author: 'Fyodor Dostoevsky',
    genre: 'Literature',
  },
  {
    id: 16,
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    genre: 'Fantasy',
  },
  {
    id: 17,
    title: 'The Lord of the Rings',
    author: 'J.R.R. Tolkien',
    genre: 'Fantasy',
  },
  {
    id: 68,
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    genre: 'Literature',
  },
  {
    id: 69,
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    genre: 'Literature',
  },
  {
    id: 70,
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    genre: 'Literature',
  },
  {
    id: 30,
    title: 'Carrie',
    author: 'Stephen King',
    genre: 'Horror',
  },
  {
    id: 31,
    title: 'The Da Vinci Code',
    author: 'Dan Brown',
    genre: 'Mystery',
  },
  {
    id: 32,
    title: 'Angels & Demons',
    author: 'Dan Brown',
    genre: 'Mystery',
  },
  {
    id: 52,
    title: '1984',
    author: 'George Orwell',
    genre: 'Science Fiction',
  },
  {
    id: 18,
    title: "Harry Potter and the Sorcerer's Stone",
    author: 'J.K. Rowling',
    genre: 'Fantasy',
  },
  {
    id: 19,
    title: 'Harry Potter and the Chamber of Secrets',
    author: 'J.K. Rowling',
    genre: 'Fantasy',
  },
  {
    id: 20,
    title: 'Harry Potter and the Prisoner of Azkaban',
    author: 'J.K. Rowling',
    genre: 'Fantasy',
  },
  {
    id: 21,
    title: 'The Hunger Games',
    author: 'Suzanne Collins',
    genre: 'Adventure',
  },
  {
    id: 22,
    title: 'Catching Fire',
    author: 'Suzanne Collins',
    genre: 'Adventure',
  },
  {
    id: 23,
    title: 'Mockingjay',
    author: 'Suzanne Collins',
    genre: 'Adventure',
  },
  {
    id: 24,
    title: 'Divergent',
    author: 'Veronica Roth',
    genre: 'Adventure',
  },
  {
    id: 25,
    title: 'Insurgent',
    author: 'Veronica Roth',
    genre: 'Adventure',
  },
  {
    id: 26,
    title: 'The Shining',
    author: 'Stephen King',
    genre: 'Horror',
  },
  {
    id: 27,
    title: 'It',
    author: 'Stephen King',
    genre: 'Horror',
  },
  {
    id: 28,
    title: 'Pet Sematary',
    author: 'Stephen King',
    genre: 'Horror',
  },
  {
    id: 29,
    title: 'The Stand',
    author: 'Stephen King',
    genre: 'Horror',
  },

  {
    id: 55,
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    genre: 'Literature',
  },
  {
    id: 56,
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    genre: 'Literature',
  },
  {
    id: 63,
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    genre: 'Literature',
  },
  {
    id: 64,
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    genre: 'Literature',
  },
  {
    id: 65,
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    genre: 'Literature',
  },
  {
    id: 66,
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    genre: 'Literature',
  },
  {
    id: 33,
    title: 'The Lost Symbol',
    author: 'Dan Brown',
    genre: 'Mystery',
  },
  {
    id: 34,
    title: 'Inferno',
    author: 'Dan Brown',
    genre: 'Mystery',
  },
  {
    id: 35,
    title: 'Origin',
    author: 'Dan Brown',
    genre: 'Mystery',
  },
  {
    id: 51,
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    genre: 'Literature',
  },
  {
    id: 53,
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    genre: 'Literature',
  },
  {
    id: 54,
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    genre: 'Literature',
  },
]
