import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { MainLayout } from '@/components/layout';
import { NextPageWithLayout } from '../models';

const Home: NextPageWithLayout = () => {
	const router = useRouter();
	function nextDetailPage() {
		router.push({
			pathname: '/posts/[postId]',
			query: {
				postId: '123',
				ref: 'social',
			},
		});
	}

	return (
		<div className={styles.container}>
			<Head>
				<title>Learning NextJS - Typescript</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href="https://nextjs.org">NGuyễn Đắc Phương code!</a>
				</h1>

				<p className={styles.description}>
					Get started by editing <code className={styles.code}>pages/index.tsx</code>
				</p>
				<button onClick={nextDetailPage}>Next to PostDetail</button>

				<div className="sty" style={{ marginTop: '2000px' }}></div>
				<Link href="/about">
					<a>Go to AboutPage</a>
				</Link>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
};
Home.Layout = MainLayout;
export default Home;
