version: '3.8'

services:
  postgres:
    container_name: postgres_container_duynghia
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-duynghia123}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5436"
    restart: unless-stopped
  
volumes:
    postgres:

#docker-compose -f postgres.yml -p hoidanit-postgres up --build -d 